### ISSUE TITLE
Deploy via github pages?

### ISSUE THREAD

**Issue by nolanbconaway** [sqlfluff/sqlfluff.com#1]
This is something I am [weirdly interested](https://nolanbconaway.github.io/blog/2020/deploying-my-pelican-website-to-github-pages.html) in, would be happy to write a workflow to deploy to pages if git is a desirable host!

**Comment by alanmcruickshank** [comment]
This is now resolved. I've migrated the whole site to netlify - which makes deployment easier 👍 . SSL is taking a little time to propagate, but should be resolved soon.

**Comment by nolanbconaway** [comment]
Holy smokes i forgot this this was #1
