### ISSUE TITLE
Incorrect link on home page

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff.com#2]
As per https://github.com/sqlfluff/sqlfluff/issues/4065 we need to change this link:

https://github.com/sqlfluff/sqlfluff.com/blob/fb25c240cdc5f4421174080743fa77871762e859/src/templates/partials/base.html#L46

At the moment this repo is private and I can't even fork it to open a PR :-(

**Comment by alanmcruickshank** [comment]
This is now resolved. I've migrated the whole site to netlify - which makes deployment easier 👍 . SSL is taking a little time to propagate, but should be resolved soon.
